### ISSUE TITLE
Please take down your dbxfs mirror

### ISSUE THREAD

**Issue by rianhunter** [vbuell/torram#14]
I do not consent to having my code on GitHub. Please take it down

**Comment by vbuell** [comment]
The code is licensed with GPL3 which clearly defines what is doce and how can it be distributed. Forks or mirrors are allowed and wecomed in OSS world, if you disagree then you probably did choose the wrong license.

**Comment by rianhunter** [comment]
I own the code, it's licensed the way I want it to be licensed. Read the license again, it's GPL3 except for a provision where it's disallowed to be hosted on GitHub. You are not allowed to host it here. https://thelig.ht/code/dbxfs/file/LICENSE.html Putting it on GitHub is not permitted by the license.

**Comment by ava1ar** [comment]
What about 44 forks here: https://github.com/rianhunter/dbxfs/network/members? Do you have concern about this particular mirror only?

**Comment by rianhunter** [comment]
Those forks predate the transition away from GitHub and none seem to be active mirrors, only containing out of date code. If any turn out to be active mirrors I will send them the same notice.

I spent many hours of my short life writing this software so people like you can study it and use it. Can you please just honor this simple request from the author? I'm just one dude, you're only hurting me.

**Comment by vbuell** [comment]
> I own the code, it's licensed the way I want it to be licensed. Read the license again, it's GPL3 except for a provision where it's disallowed to be hosted on GitHub. You are not allowed to host it here. https://thelig.ht/code/dbxfs/file/LICENSE.html Putting it on GitHub is not permitted by the license.

1. You changed it after I create a mirror (Fri Mar 25 10:55:35 2022 -0700. Hash 72d448224dd19bcfd4919846d2a07fd459670650.). So you just can't use this argument here in this request.
2. You cannot change the license without a formal agreement of all contributors. May I ask you if it was done? If not, you are hurting OSS community by violating the rights of these people. Please revert the change.

> Can you please just honor this simple request from the author? I'm just one dude, you're only hurting me.
May I ask you a tiny question? What's really behind yuor decision to make such a request? We live our "short lifes" in one small world, which is much better if we cooperate, honor the law, don't steal from each other, behave in a non destructive way... I just put a mirror of your repo here with all the credits to the original author (you), because you removed it with a history rewrite and I don't want your code disappear if something happens with your own repository. If you want me to change the description or any other metadata, just let me know.

**Comment by rianhunter** [comment]
> You changed it after I create a mirror (Fri Mar 25 10:55:35 2022 -0700. Hash 72d448224dd19bcfd4919846d2a07fd459670650.). So you just can't use this argument here in this request.

License changes can be done at any time

> You cannot change the license without a formal agreement of all contributors. May I ask you if it was done? If not, you are hurting OSS community by violating the rights of these people. Please revert the change.

There is only one code change committed by a third party and I will revert their change so that 100% of the copyrighted material is mine. This is a not a large project.

> May I ask you a tiny question? What's really behind your decision to make such a request?

I believe GitHub is a malicious company that exploits both its users and its customers.

> I just put a mirror of your repo here with all the credits to the original author (you), because you removed it with a history rewrite

Yes, it should have been clear that I did that intentionally. I have made a [public statement about my abandonment of GitHub](https://thelig.ht/abandoning-github/) which I'm sure you saw. By hosting a mirror you are openly violating my wishes. Why would you do that? I would never do such a thing to someone if it was their genuine wish, especially someone who does work that benefits me. Specifically I would never do that to you. I'm just asking for reciprocal behavior and a courtesy. If you don't want to be destructive towards others, taking down the repro is the best way to do it.

> I don't want your code disappear if something happens with your own repository.

PyPI has a backup of the code. I don't mind if you use [GitLab](https://gitlab.com/). You could also set up a mirror to https://www.archive.org/ for this purpose.

Just please understand that by hosting [the repository here](https://github.com/vbuell/dbxfs-mirror) you are taking malicious actions against the author. I should hope that I have demonstrated enough good faith by providing this code in the first place, I just ask for a similar display of good faith in return.

**Comment by vbuell** [comment]
> License changes can be done at any time

... with a number of restrictions. License never apply retroactively - it just doesn't work like that. Otherwise that would be a disaster - you should understand that.

> There is only one code change committed by a third party and I will revert their change so that 100% of the copyrighted material is mine. This is a not a large project.

You are using word "copyrighted" which is an opposite of "public domain" (which you choose). I'm really confused now and I'm not sure what meaning you put into your words.

> I believe GitHub is a malicious company that exploits both its users and its customers.

While I share this feeling partially (since Microsoft bought it it's less trusted platform), these are just personal feelings which can't collide with legal things. In this particular case, it's in your hands what to do with your project/repository, but repos/forks people have are out of your control "by design".

> Yes, it should have been clear that I did that intentionally. I have made a [public statement about my abandonment of GitHub](https://thelig.ht/abandoning-github/) which I'm sure you saw.

Yes you had to be more clear. I didn't see this info till this morning. The link is not really visible anywhere on your site.

> Just please understand that by hosting [the repository here](https://github.com/vbuell/dbxfs-mirror) you are taking malicious actions against the author. I should hope that I have demonstrated enough good faith by providing this code in the first place, I just ask for a similar display of good faith in return.

I don't see any reasons for using words like "malicious" in this situation. Again, your code is GPL, it was GPL from the beginning. We, as programmers, don't open-source the code because we want to show "good faith". Wo that because it's the right way to do and our believes.

Ok, to summarise it:

1. It's really weird that you, calling yourself a linux-friendly person, treat your code as something "copyrighted", something being controlled solely by yourself, something that you want to hide it from some parties (from github robots in this case).
2. Please educate yourself about how licensing works, what's permitted and what's not. Next time you start the new project please be more careful of what license you want to use. According to words you use (referencing "copyrighted" you used above) you might want to put your work under one of much more restrictive licenses.
3. The fact that you made so many mistakes these days (could be just because you were in hurry trying to shut down the mirror asap) might be a sign that you don't honor and follow OSS principles, which is sharing the code with no fears that someone will steal your ideas. If that's your own project, not affiliated with Dropbox of any other company, I'd advise you to be less concerning of what's happening with your code. Otherwise, please ask for a legal advice in your company.

I'll make the project private for a while, in a hope that you will make your mind and change your decision. **Please confirm** you still want me to take it down here on GitHub.

**Comment by rianhunter** [comment]
It is my wish that no active mirror of my projects exist on GitHub. If you delete the repository or make the repository private that would be much appreciated.

**Comment by vbuell** [comment]
deleted

**Comment by rianhunter** [comment]
Thank you
