### ISSUE TITLE
Rendundant package name

### ISSUE THREAD

**Issue by TanyaEleventhGoddess** [vbuell/torram#19]
This python package shares its name with https://github.com/simon-schaefer/torram used in AI development and this may cause problems in packages installation

**Comment by vbuell** [comment]
Your two issues (this one and #18) are quite hillarious. Not sure what's your proposition here. Are you asking me to rename, even though the other repo was create Mar 2022, almost ten years after this repo was created?
Also why do you call this project "redundant?". Is that because _you_ don't need it? :)
